FROM alpine:3.20

# Directory inside the assets image
WORKDIR /assets

# Copy assets
# Metabase
COPY infrastructure/metabase /assets/metabase
RUN chmod -R 755 /assets/metabase

# COPY --chmod=755 infrastructure/metabase /assets/metabase

# Postgres
COPY infrastructure/postgres /assets/postgres
RUN chmod -R 755 /assets/postgres

# Elasticsearch re-indexing
COPY infrastructure/deployment/reindex.sh /assets/elasticsearch/reindex.sh
RUN chmod -R 755 /assets/elasticsearch/reindex.sh

# FIXME: This is a workaround to prevent the on-deploy.sh script from being executed in the assets image
RUN rm -f /assets/postgres/on-deploy.sh
