# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: 'service alert'
type: 'frequency'
index: 'kibana-alert-history-services'
is_enabled: true
num_events: 1
realert:
  minutes: 5
terms_size: 50
timeframe:
  minutes: 5
timestamp_field: '@timestamp'
timestamp_type: 'iso'
use_strftime_index: false
# https://github.com/Yelp/elastalert/issues/1260
raw_count_keys: false
alert_subject: '{{HOST}} {}: {} {} 🚨'
alert_subject_args:
  - 'event.kind'
  - 'rule.name'
  - 'kibana.alert.context.apm__error_rate.serviceName'
alert_text: 'Login to https://kibana.{{HOST}}/app/apm/services/{}/overview to view the alert.'
alert_text_args:
  - 'kibana.alert.context.apm__error_rate.serviceName'
filter:
  - query:
      query_string:
        query: '@timestamp:*'
alert:
  - 'email'
email: '{{ALERT_EMAIL}}'
from_addr: 'alert@opencrvs.org'
smtp_host: '{{SMTP_HOST}}'
smtp_port: {{SMTP_PORT}}
smtp_ssl: false
smtp_auth_file: '/opt/elastalert/auth.yaml'
