# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
name: 'ssh-alert'
type: 'frequency'
index: 'kibana-alert-history-default'
is_enabled: true
num_events: 1
realert:
  minutes: 1
terms_size: 50
timeframe:
  minutes: 1
timestamp_field: '@timestamp'
timestamp_type: 'iso'
use_strftime_index: false
# https://github.com/Yelp/elastalert/issues/1260
raw_count_keys: false
filter:
  - query:
      term:
        rule.name.keyword:
          value: 'Succesful SSH login'

alert: post2
http_post2_url: 'http://countryconfig:3040/email'
http_post2_payload:
  subject: '{% raw %}{{DOMAIN}}{% endraw %}: Login to {{kibana.alert.context.__es-query.hits[0]_source.user.name}} from {{kibana.alert.context.__es-query.hits[0]_source.source.ip}} 🚨'
  html: 'Login to https://kibana.{% raw %}{{DOMAIN}}{% endraw %} to view the alert.'
  from: '{% raw %}{{SENDER_EMAIL_ADDRESS}}{% endraw %}'
  to: '{% raw %}{{ALERT_EMAIL}}{% endraw %}'
