/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 *
 * OpenCRVS is also distributed under the terms of the Civil Registration
 * & Healthcare Disclaimer located at http://opencrvs.org/license.
 *
 * Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.
 */
import * as Hapi from '@hapi/hapi'
import fetch from 'node-fetch'
import { encodeScope, Scope } from '@opencrvs/toolkit/scopes'
import { logger } from '@countryconfig/logger'
import { EVENTS_URL } from '@countryconfig/constants'

interface IntegrationConfig {
  name: string
  scopes: Scope[]
}

/**
 * Integrations to register on startup. Each entry maps to a POST /integrations
 * call against the events service.
 *
 * Registration is skipped for any name that already exists, so restarts never
 * clobber a secret a National System Admin has rotated. Credentials
 * (clientId, clientSecret) are generated by events on first registration and
 * are NOT stored here — an NSA retrieves them via the Integrations UI
 * (Configurations → Integrations → Reveal keys → Refresh secret).
 *
 * Example (MOSIP):
 * {
 *   name: 'MOSIP',
 *   scopes: [
 *     { type: 'record.register', options: { event: ['birth', 'death'] } }
 *   ]
 * }
 */
const INTEGRATIONS: IntegrationConfig[] = []

async function listIntegrationNames(bearerToken: string) {
  const res = await fetch(new URL('/integrations', EVENTS_URL).toString(), {
    method: 'GET',
    headers: { Authorization: bearerToken }
  })

  if (!res.ok) {
    throw new Error(`${res.status} ${await res.text()}`)
  }

  const integrations = (await res.json()) as { name: string }[]

  return new Set(integrations.map(({ name }) => name))
}

export async function systemReadyHandler(
  request: Hapi.Request,
  h: Hapi.ResponseToolkit
) {
  if (INTEGRATIONS.length === 0) {
    return h.response().code(200)
  }

  const bearerToken = request.headers.authorization

  let existingNames: Set<string>

  try {
    existingNames = await listIntegrationNames(bearerToken)
  } catch (error) {
    // Without the existing list we cannot tell a first registration from a
    // restart, and creating blindly would duplicate the integration and
    // invalidate the credentials already in use.
    logger.warn(
      `Skipping integration registration, listing integrations failed: ${
        error instanceof Error ? error.message : error
      }`
    )
    return h.response().code(200)
  }

  for (const integration of INTEGRATIONS) {
    if (existingNames.has(integration.name)) {
      logger.info(
        `Integration "${integration.name}" already registered, skipping`
      )
      continue
    }

    try {
      const res = await fetch(new URL('/integrations', EVENTS_URL).toString(), {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: bearerToken
        },
        body: JSON.stringify({
          name: integration.name,
          scopes: integration.scopes.map(encodeScope)
        })
      })

      if (!res.ok) {
        logger.warn(
          `Registering integration "${integration.name}" failed: ${res.status} ${await res.text()}`
        )
      } else {
        logger.info(`Integration "${integration.name}" registered successfully`)
      }
    } catch (error) {
      logger.warn(
        `Registering integration "${integration.name}" threw: ${error instanceof Error ? error.message : error}`
      )
    }
  }

  return h.response().code(200)
}
