# Will be provided as variable at helm install time
# hostname: opencrvs.localhost

ingress:
  ssl_enabled: false

storage_type: pvc

# FIXME: Decide what to do with monitoring
monitoring:
  enabled: true

backup:
  enabled: false

restore:
  enabled: false

mongodb:
  use_default_credentials: false

postgres:
  enabled: false

elasticsearch:
  use_default_credentials: false

minio:
  enabled: false
  use_default_credentials: false

redis:
  enabled: false
