# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
# OpenCRVS is also distributed under the terms of the Civil Registration
# & Healthcare Disclaimer located at http://opencrvs.org/license.
#
# Copyright (C) The OpenCRVS Authors located at https://github.com/opencrvs/opencrvs-core/blob/master/AUTHORS.

# Example IP addressses used in this file:
# 22.22.22.22 - Target staging server's IP address
# 33.33.33.33 - Second worker node in this 2-server setup
# 55.55.55.55 - This IP address is both the VPN server the server used as a bastion / jump host
# 66.66.66.66 - This IP address is the address of a backup server

all:
  vars:
    # This configuration variable blocks all access to the server, including SSH, except from the IP addresses specified below.
    # This should always be set when configuring a production server if there is no other firewall in front of the server.
    # SSH and other services should never be exposed to the public internet.
    enable_backups: true
    only_allow_access_from_addresses:
      # @todo place the IP address of your VPN server or other explicitly allowed traffic sources here
      - 167.99.195.231 # example VPN server IP address
    users:
      # @todo this is where you define which development team members have access to the server.
      # If you need to remove access from someone, do not remove them from this list, but instead set their state: absent
      - name: euan
        ssh_keys:
          - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDECqHO65UpyrrO8uueD06RxGaVVq22f152Rf8qVQQAAIGAMu6gCs7ztlZ8a3yQgSEIjM/Jl1/RqIVs6CziTEef74nLFTZ5Ufz3CLRVgdebBeSBEmhTfTUV0HLkSyNzwKFpuzJxucGd72ulPvEp6eHvyJAPJz37YcU8cjaL1v05T6s2ee99li35GlDDtCzfjVV4ZPAg5JdfWuTj41RAVC0LQhk2/NB4qEu37UxGGjhRFSjBEsS5LxI9QfvgrsHpl/VOn+soH7ZkK7kS6qRgNP/uYsXRWXhHaamcl5OX68gJWTbrW6c7PCqlbCWGnsHJswCmqPIthwXXMfC7ULDNLSKG6mslAt5Dyc8/MCr3vTW7pDyr2d0FvvY86SMQUggxv3qF7TZewqfX1bhK0fMLarIxVMQ1RFo//wN9QGA+2we8rxd2Y1Kr1DBuJyuwXPfv+Exo8yNYQ+x/AYH5k6UVcSYuaB8eYmplG2KQCxt8RBFtoChrwOKNRWLqXdKyfpdp5XmnnWxPvR95gf3h3yLocVYkF0i0uvKKJ0vt8J0Ezfkdfow0B1kUg5bPXKJROX7PwbaCPdYcxyDaO6wwOigRnSmoFvkH1pLb4j1RQAXcX531CHgfN6Izi/h0mpMS4bnyIUcv2GQr+h4z4TxcCtj7qpH2y6yw7XG12jVh7TfeesXG2Q== euanmillar77@gmail.com
        state: present
        sudoer: true

docker-manager-first:
  hosts:
    opencrvs-countryconfig-prod-01: # @todo set this to be the hostname of your target server
      ansible_host: '167.172.57.239' # todo set this to be the hostname of your target server
      data_label: data1
      # @todo as production servers are not directly accessible from the internet, you need to use a jump server to access them.
      ansible_ssh_common_args: '-J jump@countryconfig-qa.opencrvs.org -o StrictHostKeyChecking=no'

# @todo We recommend you add 2-4 workers for a scaled production deployment
# This should depend on the size of your country and the number of end users.
docker-workers:
  hosts:
    opencrvs-countryconfig-prod-02: # @todo set this to be the hostname of your target server
      ansible_host: '134.122.110.42'
      data_label: data2
      ansible_ssh_common_args: '-J jump@countryconfig-qa.opencrvs.org -o StrictHostKeyChecking=no'

backups:
  hosts:
    opencrvs-countryconfig-backup:
      ansible_host: '167.99.92.15'
