name: Provision environment
run-name: Provision ${{ github.event.inputs.environment }}
on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Machine to provision
        default: qa
        required: true
        options:
          - development
          - staging
          - qa
          - production
          - backup
          - jump
          - e2e
          - v17
      tag:
        type: choice
        description: Select group tag you want to execute
        default: all
        options:
          - all
          - application
          - backups
          - checks
          - crontab
          - data-partition
          - decrypt
          - deployment
          - docker
          - elasticsearch
          - fail2ban
          - jump
          - mongodb
          - swap
          - swarm
          - tools
          - traefik
          - ufw
          - updates
          - users
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: true
      tag:
        type: string
        description: Environment to deploy to
        default: all
jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
        - name: Test variables
          run: |
            echo "environment: ${{ github.event.inputs.environment }}"
            echo "tag: ${{ github.event.inputs.tag }}"
