# All OpenCRVS services will be available under domain:
# hostname: opencrvs.localhost

# Access OpenCRVS services at http://opencrvs.localhost
# If SSL is enabled, You need to accept SSL Certificate on localhost for multiple endpoints:
# - login
# - register
# - countryconfig
# - config
# - client
# - ...
# That makes it easier to test the application locally without SSL
# On local environment SSL is disabled by default:
ingress:
  ssl_enabled: false

# On local environment services are exposed at NodePort as well and are available from Tilt
# To access service you need to click on the service name in Tilt UI:
service_type: NodePort

# Horizontal Pod Autoscaler (HPA) configuration:
# Disabled by default for local environment.
hpa:
  enabled: false

# Pod Disruption Budget (PDB) configuration:
# Disabled by default for local environment.
pdb:
  enabled: false

elasticsearch:
  auth_mode: auto
  # Copy  elasticsearch-admin-user from opencrvs-deps-qa namespace into opencrvs-qa namespace
  host: elasticsearch.opencrvs-deps-qa.svc.cluster.local
  admin_user_secret_name: elasticsearch-admin-user

# With Azure Storage we need to create secret minio-opencrvs-users
# https://github.com/opencrvs/opencrvs-helm-charts/tree/develop/charts/opencrvs-services#minio-secret-miniousers_secret
minio:
  auth_mode: use_secret
  # Copy minio-opencrvs-users from opencrvs-deps-qa namespace into opencrvs-qa namespace
  host: minio-0.minio.opencrvs-deps-qa.svc.cluster.local
  users_secret: minio-opencrvs-users

mongodb:
  auth_mode: auto
  # Copy mongodb-admin-user from opencrvs-deps-qa namespace into opencrvs-qa namespace
  admin_user_secret_name: mongodb-admin-user
  host: mongodb-0.mongodb.opencrvs-deps-qa.svc.cluster.local

redis:
  auth_mode: use_secret
  # Create redis-opencrvs-users secret in opencrvs-qa namespace with Redis credentials
  # Credentials need to be taken fro Azure Cache for Redis instance
  # Use secret specification: https://github.com/opencrvs/opencrvs-helm-charts/tree/develop/charts/opencrvs-services#redis-secret-redisusers_secret
  users_secret: redis-opencrvs-users
  host: <define redis host/endpoint here>
  port: <define redis port here>

postgres:
  auth_mode: auto
  host: <define postgres host/endpoint here>
  port: <define postgres port here>
  # Create postgres-admin-user secret in opencrvs-qa namespace with Postgres credentials
  # Credentials need to be taken from Azure Database for PostgreSQL instance
  # Use secret specification:
  # https://github.com/opencrvs/opencrvs-helm-charts/tree/develop/charts/opencrvs-services#postgres-secrets

image:
  # Use latest version from https://github.com/opencrvs/opencrvs-core/actions/workflows/build-images-from-branch.yml
  tag: 9b463e3

countryconfig:
  image:
    repository: <your dockerhub account>/<image name>
    tag: <image tag>
